# docker-compose-prod.yml
version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: e-mission/opdash:0.0.1
    ports:
      - "8050:8050"
    environment:
      DASH_DEBUG_MODE: "False"
      DASH_SERVER_PORT: 8050
      DB_HOST: db
      WEB_SERVER_HOST: 0.0.0.0
      SERVER_BRANCH: master
      CONFIG_PATH: "https://raw.githubusercontent.com/e-mission/nrel-openpath-deploy-configs/main/configs/"
      STUDY_CONFIG: "stage-program"
      AUTH_TYPE: "basic" # the other option is cognito
      REACT_VERSION: "18.2.0"
    networks:
       - emission
    deploy:
      restart_policy:
          condition: on-failure
    depends_on:
      - db
  db:
    image: mongo:4.4.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-data:/data/db
    networks:
       - emission

networks:
  emission:

volumes:
  mongo-data:
